### ISSUE TITLE
Configure proxy in docker container

### ISSUE THREAD

**Issue by MelvinKool** [stevespringett/dependency-track#101]
Currently, it's hard to set custom proxy settings on the docker machine.
#99 Would solve this problem by using environment variables.
I guess currently a workaround would be using the JAVA_OPTIONS environment variable to set the proxy?
If so, what would be the right syntax?
Is it possible to use the functionality introduced by #78 to set the proxy settings for the docker container?

**Comment by stevespringett** [comment]
Yes, #99 is a good idea and I'll try to get that into the v3.0 release. There are other options in application.properties that you'll also want to configure such as LDAP and external database settings.

I have not tried this, but the system property `alpine.application.properties` could be set to `/data/application.properties`. This file would have to exist on the Docker volume of course, but that is the intended purpose of having a persistent Docker volume, to store the application configuration, keys, etc that it needs to function. 

Once you have the properties file on the Docker data volume, you can edit the proxy, ldap, jdbc settings to your liking. I agree that this will eventually need to be made easier.

**Comment by stevespringett** [comment]
BTW, if you experiment with this and come up with a solution that works, I'd be interesting in the steps taken. This should eventually make its way into the docs as there will be other folks asking similar questions.

**Comment by stevespringett** [comment]
See also: <https://docs.dependencytrack.org/getting-started/configuration/>

**Comment by stevespringett** [comment]
Closing. Setting http_proxy (and derivatives) works
