### ISSUE TITLE
node.js scanning not working properly

### ISSUE THREAD

**Issue by eoftedal** [stevespringett/dependency-track#106]
package.json
```
{
  "name": "testproject",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "dependencies": {
    "express": "^1.0.8"
  },
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC"
}
```

I run `npm install`, and the `dependency-check --format XML --project testproject -s .`. I then upload the resulting `dependency-check-report.xml` to DependencyTracker through /api/v1/scan.
The report is imported, but neither `express` nor the transitive dependency `connect` is marked as vulnerable even though `nsp` sees them as vulnerable, and they are both marked as vulnerable in `dependency-check-report.xml`

**Comment by stevespringett** [comment]
Support for the ongoing scanning of Node components (via NSP) is currently a piece that still needs to be completed. There's a few things that need to be completed including:

- Identify and fix the reported issue
- Dynamically build purls if enough quality (high/highest) evidence is known
- Use the purl to determine ecosystem
- If the ecosystem is Node, then:
  - Dynamically create a package.json with all other Node components in the system

**Comment by stevespringett** [comment]
There was a minor persistence issue, but the primary cause for this defect is logic in ODT that actually removes vulnerabilities from components. This feature is intended to adapt to users applying suppressions, support for better identification of vulnerabilities, etc.

But in order for removal to be effective, the system needs to support identification using all available sources, and as of today, it doesn't. 

So, I've commented out the removal logic until the bullet points above are implemented including using purl to store and identify ecosystems, and using that info to trigger dynamic package.json and analysis through NSP.
