### ISSUE TITLE
Feature: Sorting/filtering of components under a project

### ISSUE THREAD

**Issue by eoftedal** [stevespringett/dependency-track#109]
Priority 1: Sort on vulnerability column
Priority 2: Filters (show only with vuln, show only with high vuln etc.)

**Comment by stevespringett** [comment]
Duplicates #91 but provides a bit more detail.

**Comment by stevespringett** [comment]
Pagination and filtering is built into the platform by design. I have not exposed that functionality yet but plan on doing so. This should be an easy enhancement but will require a lot of regression testing (mainly with the API).

**Comment by stevespringett** [comment]
The majority of tables can now be sorted. Will be included in 3.1.
