### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by vsaar** [stevespringett/dependency-track#11]
I'm trying to get Dependency Track running, but I don't know how to properly setup a user with admin rights. I used the signup link on the login page, but the created user apparently isn't allowed to create applications, etc.

Could you please provide some instructions regarding a working setup?

P.S.: I'm using the latest snapshot version, i.e. HEAD.

**Comment by stevespringett** [comment]
Installation instructions are not part of the Wiki.
https://github.com/stevespringett/dependency-track/wiki
