### ISSUE TITLE
mysql_connectors JDBC Driver identified as MySQL Server

### ISSUE THREAD

**Issue by Dakang** [stevespringett/dependency-track#115]
mysql-connector-java-5.1.34-bin.jar pulls 401 vulnerabilities, most of which seem to be listed against MySQL Server.
![1](https://user-images.githubusercontent.com/6519398/37995639-650e08b4-31d2-11e8-9fc8-fe099e615839.png)

**Comment by stevespringett** [comment]
This is a limitation of Dependency-Check. The Dependency-Check global suppression requires the  component be specified in the following format in order for the CVEs to be suppressed.

group: mysql
artifact: mysql-connector-java

https://github.com/jeremylong/DependencyCheck/blob/master/core/src/main/resources/dependencycheck-base-suppression.xml#L1090

If this is not possible, then you may need to use Dependency-Track's global suppression capability. Refer to https://docs.dependencytrack.org/triage/suppressions/

**Comment by Dakang** [comment]
Thank you for sharing this link.  I wasn't aware of the base-suppression.xml.
