### ISSUE TITLE
creating a new version of a project is impossible

### ISSUE THREAD

**Issue by stboiss** [stevespringett/dependency-track#118]
when i create a new version of a project, i have this error !
![screenshot 2018-03-29 11-33-09 001](https://user-images.githubusercontent.com/24654609/38081885-702975b6-3345-11e8-89fc-6bdbfce20168.png)

**Comment by stevespringett** [comment]
Fixed in commits:
3.0.x (bd17098f2b32e9a1cced2b2c3a2b8646889bc8b3)
master (127d8dfa6630f7a39434aa011fd4f08d89717b03)

Once 3.0.1 is released (within the next few days), go ahead and follow the instructions here: Refer to https://github.com/stevespringett/dependency-track/blob/3.0.x/upgrade
