### ISSUE TITLE
Vulnerability suppression through API and UI

### ISSUE THREAD

**Issue by eoftedal** [stevespringett/dependency-track#121]
It would be beneficial to be able to suppress vulnerabilities or matchings through the UI and through the API.

There are at least two reasons to suppress:
- files are mismatched - typically a client library for a database will sometimes be matched with vulnerabilities which only affect the server - in this case one might one to suppress on a global scale (all projects)
- vulnerable functionality is not used - a vulnerability exists in a (transitive) library, but the vulnerable functionality is not in use (or other mitigations are in place)

In both cases a mandatory suppression reason/justification should be provided

**Comment by eoftedal** [comment]
More information about how the matching is performed would also be useful. Which parts of the component information was used to match which parts of the NVD information etc.

**Comment by stevespringett** [comment]
Duplicate of #65 - This is scheduled for inclusion in 3.1. 

I plan on documenting how the matching works.

**Comment by eoftedal** [comment]
Ok, we can close this, but please include both types of suppression in #65, because they are very different in nature (wrong matching vs. mute for specific project)
