### ISSUE TITLE
Invalid default value for 'LAST_OCCURRENCE'

### ISSUE THREAD

**Issue by znb** [stevespringett/dependency-track#124]
Getting this exception thrown when I start up DT via the standalone WAR file.

`13:16:40.840 ERROR [Datastore] Error thrown executing CREATE TABLE `PORTFOLIOMETRICS`
(
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `COMPONENTS` INTEGER NOT NULL,
    `CRITICAL` INTEGER NOT NULL,
    `FIRST_OCCURRENCE` TIMESTAMP NOT NULL,
    `HIGH` INTEGER NOT NULL,
    `RISKSCORE` DOUBLE NOT NULL,
    `LAST_OCCURRENCE` TIMESTAMP NOT NULL,
    `LOW` INTEGER NOT NULL,
    `MEDIUM` INTEGER NOT NULL,
    `PROJECTS` INTEGER NOT NULL,
    `SUPPRESSED` INTEGER NOT NULL,
    `VULNERABILITIES` INTEGER NOT NULL,
    `VULNERABLECOMPONENTS` INTEGER NOT NULL,
    `VULNERABLEPROJECTS` INTEGER NOT NULL,
    CONSTRAINT `PORTFOLIOMETRICS_PK` PRIMARY KEY (`ID`)
) ENGINE=INNODB : Invalid default value for 'LAST_OCCURRENCE'
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Invalid default value for 'LAST_OCCURRENCE'`

Dependency Track: 3.0.2
Alpine: 1.1.1
MySQL Connector: 5.1.46
MySQL Server: 5.7.21-0ubuntu0.16.04.1
Ubuntu: 16.04LTS

Please let me know if you need any more information.

**Comment by znb** [comment]
Apologies...this appears to be related to the **NO_ZERO_IN_DATE,NO_ZERO_DATE** settings in MySQL. 

I've updated my MySQL configuration and it appears to be working as required. 

I added the following line to /etc/mysql/conf.f/mysql.cnf

`
[mysqld]
sql_mode="STRICT_TRANS_TABLES,ONLY_FULL_GROUP_BY,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
`

**Comment by stevespringett** [comment]
Perfect. Glad it's working. I think I'll enhance the docs a bit to include the sql_mode example you provided.
