### ISSUE TITLE
dependencyTrackPublisher artifact: 'dependency-check-report.xml', artifactType: 'scanResult', projectId: 'Unable to retrieve projects. Received status code: 404'

### ISSUE THREAD

**Issue by Mortagne** [stevespringett/dependency-track#129]
Hi, i can't find why ... no log or more info...

When i go in **Jenkins -> Pipeline Syntax: Snippet Generator**

I chose dependencyTrackPublisher ... for projectId, i receive this message : **'Unable to retrieve projects. Received status code: 404'**

I create my project in dependency-track, i have this id, in URL ... a5b42356-3608-4513-8f56-35dc70690402

if i try to run the snippet in my pipeline : 
`dependencyTrackPublisher artifact: 'dependency-check-report.xml', artifactType: 'scanResult', projectId: 'a5b42356-3608-4513-8f56-35dc70690402'`

so i receive this error :
`
[Pipeline] [Analyse Code Security] dependencyTrackPublisher
[Analyse Code Security] [DependencyTrack] Publishing artifact to Dependency-Track
[Pipeline] [Analyse Code Security] echo
[Analyse Code Security] Exception thrown:
[Analyse Code Security]  java.lang.NullPointerException
[Pipeline] [Analyse Code Security] echo
[Analyse Code Security] Stacktrace:
[Pipeline] [Analyse Code Security] }
[Pipeline] [Analyse Code Security] // script
[Pipeline] [Analyse Code Security] }
[Pipeline] [Analyse Code Security] // withEnv
[Pipeline] [Analyse Code Security] }
[Pipeline] [Analyse Code Security] // stage
[Pipeline] [Analyse Code Security] }
`
i have a jenkins prod server.
I install in my local docker environnement Dependency-Track and port 8080 is open.
The server can ping and wget on my http:/ip:8080/

I setup the "Dependency-Track URL" and "API key" in my Master Jenkins server.

.... so i don't understand why this don't work ... i don't see any errors in logs or something.

Regards
Mortagne

**Comment by stevespringett** [comment]
I assume you followed the instructions here: https://docs.dependencytrack.org/integrations/jenkins/ ?

**Comment by stevespringett** [comment]
I noticed in your example you specified: http:/ip:8080/

In your example, there is a trailing slash. In the docs, there isn't a trailing slash. I don't know if that matters or not, but I'd try without the trailing slash and report back.

**Comment by Mortagne** [comment]
no no, it's a typo ... i enter http://x.y.z.a:8080/

yes i follow the instruction ... so i don't use standard pipeline job ... i use Declarative Pipeline, it's work with this ?

Regards,
Mortagne

**Comment by stevespringett** [comment]
Remove the trailing slash. I've confirmed this to be an issue with the Jenkins plugin.

Change http://x.y.z.a:8080/ to http://x.y.z.a:8080

**Comment by Mortagne** [comment]
Ok, i remove the trailling slash ...

so now, i have this error : 
**projectId: 'Unable to retrieve projects. Received status code: 403'**

**Comment by stevespringett** [comment]
Add the VIEW_PORTFOLIO permission to the automation team. This permission is necessary to view a list of available projects.

**Comment by Mortagne** [comment]
So ... i see this error ...
`02:47:53.985 INFO [AuthorizationFilter] Unauthorized access attempt made by API Key qQitEE9Zjjm1J5sZ0XY58iz9lf8FOnnM to http://x.y.z.a:8080/api/v1/project`

i have a default user "Automation" with the API Key in code snippet....

**Comment by stevespringett** [comment]
The VIEW_PORTFOLIO permission has been added as a default for all new installations going forward. However, please add the permission to resolve the issue. Example:
<img width="809" alt="add-view-portfolio-permission" src="https://user-images.githubusercontent.com/3878933/38534047-8f7e11f6-3c41-11e8-8cf9-b048e34d20e0.png">

**Comment by Mortagne** [comment]
Hi, "merci" for the information, I make some changes ...

So ... in my pipeline log, I have ... this log...
`Analyse Code Security] [DependencyCheck] Scanning: /data/apps/jenkins/workspace/es_feature_dependency-track-V5T47FTKEHQCQF7C47KJDQ3TTY44MOTYOA2O6OSX2EJIFIW6JHGQ
[Analyse Code Security] [DependencyCheck] Analyzing Dependencies
[Pipeline] [Analyse Code Security] dependencyCheckPublisher
[Analyse Code Security] [DependencyCheck] Collecting Dependency-Check analysis files...
[Analyse Code Security] [DependencyCheck] Searching for all files in /data/apps/jenkins/workspace/es_feature_dependency-track-V5T47FTKEHQCQF7C47KJDQ3TTY44MOTYOA2O6OSX2EJIFIW6JHGQ that match the pattern **/dependency-check-report.xml
[Analyse Code Security] [DependencyCheck] Parsing 1 file in /data/apps/jenkins/workspace/es_feature_dependency-track-V5T47FTKEHQCQF7C47KJDQ3TTY44MOTYOA2O6OSX2EJIFIW6JHGQ
[Analyse Code Security] [DependencyCheck] Successfully parsed file /data/apps/jenkins/workspace/es_feature_dependency-track-V5T47FTKEHQCQF7C47KJDQ3TTY44MOTYOA2O6OSX2EJIFIW6JHGQ/dependency-check-report.xml with 25 unique warnings and 0 duplicates.
[Pipeline] [Analyse Code Security] script
[Pipeline] [Analyse Code Security] {
[Pipeline] [Analyse Code Security] dependencyTrackPublisher
[Analyse Code Security] [DependencyTrack] Publishing artifact to Dependency-Track`

i surround my code by "try/catch" so ... I see nothing.

Nothing in "dependency-track.log" on the docker "machine"
Nothing Jenkins logs under "org.owasp"

so ... in the interface of Dependency-Track ... I see nothing under my project...

some ideas ?

**Comment by Mortagne** [comment]
In before execution, my global job fails ...

if I comment the call to "dependencyTrackPublisher " ... my job finish with success

**Comment by Mortagne** [comment]
with the documentation .. 
I try this : 
`curl -X "PUT" "http://dtrack.example.com/api/v1/scan" \
     -H 'Content-Type: application/json' \
     -H 'X-API-Key: LPojpCDSsEd4V9Zi6qCWr4KsiF3Konze' \
     -d $'{
  "project": "f90934f5-cb88-47ce-81cb-db06fc67d4b4",
  "scan": "PD94bWwgdm..."
  }'`

so after I pass my .xml file in base64 ... it's big... I have this error ... /usr/bin/curl: Argument list too long

**Comment by Mortagne** [comment]
With a smallest file ... it's work ... so... I can't use the full report ... do you have a idea ??? bash mode or others way ...

anyway ... via Jenkins, I can't execute the analysis ...

**Comment by Mortagne** [comment]
a example of my dependency-check-report.xml....

[dependency-check-report_msc_services.xml.zip](https://github.com/stevespringett/dependency-track/files/1904917/dependency-check-report_msc_services.xml.zip)

**Comment by Mortagne** [comment]
With a colleague, i found a solution to upload a large file by curl.

first, create a file contains this information :

`
{
  "project": "a5b42356-3608-4513-8f56-35dc70690402",
  "scan": "your data of xml file in Base64"
}
`
And just call curl with file annotation '@'

`
curl -X "PUT" "http://localhost:8080/api/v1/scan" \
     -H 'Content-Type: application/json' \
     -H 'X-API-Key: qQitEE9Zjjm1J5sZ0XY58iz9lf8FOnnM' \
     -d @input.txt
`

**Comment by stevespringett** [comment]
Updated docs containing example available here: https://docs.dependencytrack.org/usage/cicd/
