### ISSUE TITLE
upload gzip ODC report

### ISSUE THREAD

**Issue by stboiss** [stevespringett/dependency-track#136]
can you add the ability to upload a compressed ODC report in 3.0.x ?

**Comment by stevespringett** [comment]
I'll try to add this in 3.1. Ideally, support for gzip and zip should both be supported.

**Comment by stboiss** [comment]
@stevespringett , do you have any idea when version 3.1 will be released ?

**Comment by stevespringett** [comment]
I’m doing quarterly releases. 3.1 will be released in June.
