### ISSUE TITLE
ODC relatedDependencies are not insert in component

### ISSUE THREAD

**Issue by stboiss** [stevespringett/dependency-track#137]
ODC relatedDependencies are not insert in component when I upload scan

example : 
```
<dependency isVirtual="false">
  <fileName>jackson-core-2.9.4.jar</fileName>
  <filePath>
     /cache/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.4/jackson-core-2.9.4.jar
  </filePath>
  <md5>13dea2ed252059d3a1b942bd531c2598</md5>
  <sha1>a9a71ec1aa37da47db168fede9a4a5fb5e374320</sha1>
  <description>
    Core Jackson processing abstractions (aka Streaming API), implementation for JSON
  </description>
  <license>http://www.apache.org/licenses/LICENSE-2.0.txt</license>
  <projectReferences>
    <projectReference>awesome-f5-cli-launcher:compile</projectReference>
  </projectReferences>
  <relatedDependencies>
    <relatedDependency isVirtual="false">
      <filePath>
        /cache/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-csv/2.9.4/jackson-dataformat-csv-2.9.4.jar
      </filePath>
      <sha1>6a296e8a971177cb2df3f9e08f6c2526cff19443</sha1>
      <md5>6ff6127c2c536f09a6d32501bbe347df</md5>
      <identifier type="maven">
        <name>
          com.fasterxml.jackson.dataformat:jackson-dataformat-csv:2.9.4
        </name>
        <url>
          http://search.maven.org/#search|ga|1|1%3A%226a296e8a971177cb2df3f9e08f6c2526cff19443%22
        </url>
      </identifier>
    </relatedDependency>
  </relatedDependencies>
...
```

**Comment by stevespringett** [comment]
This will be included in v3.1

**Comment by stboiss** [comment]
@stevespringett ,
insertion of related dependencies is not clean !
for : 
```
<dependency isVirtual="false">
            <fileName>shiro-core-1.2.6.jar</fileName>
            <filePath>/cache/.m2/repository/org/apache/shiro/shiro-core/1.2.6/shiro-core-1.2.6.jar</filePath>
            <md5>60d0842ce6db6a50204814f0953b2d5b</md5>
            <sha1>3c43bfc33849d6724846b9d6a52171e7e7aacb82</sha1>
            <description>Apache Shiro is a powerful and flexible open-source security framework that cleanly handles        authentication, authorization, enterprise session management, single sign-on and cryptography services.</description>
            <license>http://www.apache.org/licenses/LICENSE-2.0.txt</license>
            <projectReferences>
                <projectReference>bcmc :: extranet:compile</projectReference>
            </projectReferences>
            <relatedDependencies>
                <relatedDependency isVirtual="false">
                    <filePath>/cache/.m2/repository/org/apache/shiro/shiro-web/1.2.6/shiro-web-1.2.6.jar</filePath>
                    <sha1>0d719ecdf14103e6e51133d6b926e52906616cc4</sha1>
                    <md5>6bc0fab9c546644b9b5229a8f8843223</md5>
                    <identifier type="maven">
                        <name>org.apache.shiro:shiro-web:1.2.6</name>
                        <url>http://search.maven.org/#search|ga|1|1%3A%220d719ecdf14103e6e51133d6b926e52906616cc4%22</url>
                    </identifier>
                </relatedDependency>
            </relatedDependencies>
```
I have 
![screenshot 2018-05-15 16-27-17 001](https://user-images.githubusercontent.com/24654609/40063110-dfa29c06-585c-11e8-86ec-21bebe11d599.png)

**Comment by stevespringett** [comment]
It appears that the identifier on relatedDependencies is only used for Maven projects which greatly reduces the usefulness of the element. It also appears the dependency-check schema is inconsistent between dependency and relatedDependency. One has a list of identifiers, the other only has a single identifier without any evidence. Both of these have to map back to a single Dependency object so it needs to be able to account for both a list of nodes and a single node with different names.

In addition, the identifier on the dependency node has a slightly different format than the single identifier on the relatedDependency node.

Accounting for these differences will make the parser more fragile and susceptible to being broken at any point in time when the schema and formats change to be consistent.

To fix the issue would be to fix the dependency-check schema and the format of the data in the resulting document. However, this will still be susceptible to being broken (like it is now). I propose that the Dependency-Check project implement the Package URL specification (like Dependency-Track has) to ensure that the ecosystem and metadata about the component have a structured, predictable, and supportable format. If every dependency and relatedDependency node had a resulting Package URL element (at least for the dependencies that we can (maven, npm, etc)), then that would be the ideal thing to do.
