### ISSUE TITLE
execute metrics update for a project after upload

### ISSUE THREAD

**Issue by stboiss** [stevespringett/dependency-track#141]
is it possible to execute metrics update for a project immediately after  Dependencycheck analysis after uploading scan ?

**Comment by stevespringett** [comment]
REST APIs exist for refreshing metrics on individual components, individual projects, or the entire portfolio. Calling the refresh API immediately after upload can be done, but the platform will not do it on its own.

Perform a refresh simply by sending a GET request to:
`/api/v1/metrics/project/{uuid}/refresh`
A 200 will be immediately sent back (assuming the UUID of the project can be found), and the metrics will be immediately scheduled.

The entire portfolio metrics are updated every hour. v3.0 include a button on the dashboard to trigger a portfolio metric update in the UI. v3.1 extends this capability to individual projects and components.

**Comment by stboiss** [comment]
@stevespringett, 
if i call /api/v1/metrics/project/{uuid}/refresh immediatly after upload, are yousure that the refresh will be done after the vulnerabilities analysis ?

**Comment by stevespringett** [comment]
If the call is made immediately after the upload, then no, there is no guarantee the refresh will occur after the upload has been processed and scanned. It _could_ happen, but no guarantees. Alpine (and thus Dependency-Track) performs a lot of async tasks in an effort to maximize performance by utilizing all available CPU cores.

I'm making some changes in Alpine which will allow for the capability to specify onSuccess and onFailure callbacks in an unbounded chain of events. So in Dependency-Track v3.1, a project will automatically be refreshed after a scan/bom has been uploaded and the components analyzed.

**Comment by stevespringett** [comment]
I've tested this functionality and it works as intended.

**Comment by stboiss** [comment]
@stevespringett, thank's
