### ISSUE TITLE
View suppressed vulnerability in Component view in 3.1

### ISSUE THREAD

**Issue by stboiss** [stevespringett/dependency-track#152]
I suppressed vulnerability on Component view but after refresh I don't view this suppressed vulnerability in order to correct or comment.

Can you add possibility to view suppressed vulnerability in Component view like in Project View

**Comment by stevespringett** [comment]
### Audit Mode: Disabled
![audit-mode-disabled](https://user-images.githubusercontent.com/3878933/40194570-805baf2e-59d0-11e8-90e9-6e1b944887f8.png)

### Audit Mode: Enabled
![audit-mode-enabled](https://user-images.githubusercontent.com/3878933/40194584-903394f2-59d0-11e8-9716-79714f010413.png)
