### ISSUE TITLE
authorize external ODC execution to access to NVD Mirror

### ISSUE THREAD

**Issue by stboiss** [stevespringett/dependency-track#155]
Can you authorize external ODC execution to access to NVD Mirror folder ?

**Comment by stevespringett** [comment]
This was a feature in v1 and I intended this to make it into v3, but somehow it was overlooked. I'm adding it now and will be included in the upcoming v3.1.0 release.

**Comment by stevespringett** [comment]
Complete. The NVD mirror is accessible at: http://hostname/mirror/nvd

This will be included in v3.1.0.

**Comment by stevespringett** [comment]
Example Dependency-Check config:
```ini
cveUrl12Modified=http://hostname/mirror/nvd/nvdcve-modified.xml.gz
cveUrl20Modified=http://hostname/mirror/nvd/nvdcve-2.0-modified.xml.gz
cveUrl12Base=http://hostname/mirror/nvd/nvdcve-%d.xml.gz
cveUrl20Base=http://hostname/mirror/nvd/nvdcve-2.0-%d.xml.gz
```

**Comment by stboiss** [comment]
@stevespringett thank's
