### ISSUE TITLE
Unmarshalling exception when uploading from Jenkins -> Dependency Track (version git: 4b4b0975bd7a9)

### ISSUE THREAD

**Issue by MichaelGissingNC** [stevespringett/dependency-track#163]
Hi Steve,

* I built the latest commit from git (4b4b0975bd7a9) and uploaded it to the server
* Jenkins: dependency check plugin 3.2.1
* I get an Exception in ScanUploadProcessingTask:

```
2018-06-07 17:40:54,221 [] ERROR [org.owasp.dependencytrack.tasks.ScanUploadProcessingTask] Error while processing scan result
2018-06-07 17:40:54,221 [] ERROR [org.owasp.dependencytrack.tasks.ScanUploadProcessingTask] javax.xml.bind.UnmarshalException
 - with linked exception:
[javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
Message: Premature end of file.]
```

* To check if the XML report itself is OK, I uploaded it via curl manually, it worked.

I can provide the report XML tomorrow if you need it - would need to clean up confidential information first. Let me know if you are interested.

**Comment by stevespringett** [comment]
If you're testing with Dependency-Track 3.1 snapshot, there's improvement in error handling #162 which should help diagnose the issue. If you're still not able to figure it out or need me to make changes in order to reproduce, send me the file, attached to this ticket or via email (steve.springett@owasp.org).

**Comment by MichaelGissingNC** [comment]
Thanks for the help Steve, I figured it out, although the hint to the cause was already in the original message. In contrast to the DependencyCheckPublisher, the DependencyTrackPublisher doesn't have a default value for artifact and returns success in this case.

I'll close this issue and open an issue with jenkinsci/dependency-check-plugin

**Comment by MichaelGissingNC** [comment]
https://github.com/jenkinsci/dependency-check-plugin/pull/25

**Comment by stevespringett** [comment]
Glad you figured it out and thanks for the PR
