### ISSUE TITLE
No any data shown in the portal

### ISSUE THREAD

**Issue by willpowerforever** [stevespringett/dependency-track#18]
Hi Steve,

The idea of this project looks great. I deployed and started the application. But I didn't see any data in from the portal. I add a component but then how should I trigger it to show me all vulnerabilities for this component? Is this function already available? If yes, could you please provide a more information in the document?

Thanks!
William

**Comment by stevespringett** [comment]
Once a component is added, it will be automatically scanned. The scanning usually kicks off within a minute of it being added. 

Scans are also automatically started upon the war being deployed (as in a server startup). Scans will then the run every 24 hours.
