### ISSUE TITLE
Html/XML reports Error 500

### ISSUE THREAD

**Issue by CalldiDoctor** [stevespringett/dependency-track#19]
Hi,

I have found a problem in the HTML and XML reporting.
Almost always (just once i could access) I get an 500 error after clicking on HTML or XML button (http://localhost:8080/dtrack/dependencyCheckReport/2.html).
I can't figure out why has just worked once.

I'm using a tomcat 8 for the deploy.

Thanks!

**Comment by stevespringett** [comment]
I believe this issue is resolved. If you could, checkout the master branch, compile, and deploy the new war to your Tomcat installation.

**Comment by CalldiDoctor** [comment]
I have downloaded and compiled the code, and the problem still occurs. 
However, I've reporoduced the error. The error appears once you access to the application for the first time, before any vulnerability analysis has been performed.
If you create a new component, the search engine starts to process the new component, and then you are able to access the XML and Html reports of every application.

I hope this helps.

**Comment by stevespringett** [comment]
When the servlet container deploys dependency track, it will automatically start a scan. Are you saying that the error occurs between the startup and the start of the first scan?

With the changes I made the other day ( 75deb7aea6e8230dcc4402190fccb31ecc637afd ), I'm unable to reproduce the error. Can you provide exact steps and the stacktrace?

**Comment by CalldiDoctor** [comment]
True, I'm not able to reproduce this error anymore.
Sorry for the noise

**Comment by stevespringett** [comment]
If you run into the issue again, I'll reopen the ticket.
