### ISSUE TITLE
default login seems not to work

### ISSUE THREAD

**Issue by bdynamic** [stevespringett/dependency-track#34]
I installed dependency track in a tomcat7 environment running on ubuntu and also get the login screen but the default login credentials admin/admin do not work (athentication failure invalid username or password)

**Comment by stevespringett** [comment]
Did you deploy the war for version 1.0, or did you compile from the master branch?

**Comment by bdynamic** [comment]
I used the pre compiled version 1.0 and installed it via the tomcat7 manager webgui

**Comment by KonstantinShemyak** [comment]
I'm having the same problem: a freshly-installed precompiled WAR version 1.0 does not allow login with admin/admin. As one may guess, this is a complete blocker :-)

**Comment by mafyzz** [comment]
Hello, i'm having problems with default login in both versions, pre-compiled (.WAR)and compiled from source code. I installed it via the tomcat8 manager webgui to.
Is there any way to access the app?

**Comment by KonstantinShemyak** [comment]
I was able to login into the compiled `master` (b553c753ee4c63b505613c92bb0f7443a4c62db6) when run as Spring Boot app.

**Comment by mafyzz** [comment]
can you deploy the compiled version? i tried to compile and access and app works but login doesn't

**Comment by KonstantinShemyak** [comment]
Tomcat log contained errors saying that the server cannot create files under `/usr/share/tomcat8/dependency-track`. My `/usr/share/tomcat8` was owned by `root:root` and had permissions 755, so Tomcat could not create directory `dependency-track` there. I do not know what should be the proper fix, but to get Dependency Track running I changed `/usr/share/tomcat8` to be owned by `tomcat8:tomcat8`. It accepts "admin/admin" now.

**Comment by kevinfealey** [comment]
I know this is an old issue, but I just downloaded the 1.0.0 GA release from [OWASP](https://bintray.com/artifact/download/stevespringett/owasp/org/owasp/dependency-track/1.0.0/dependency-track-1.0.0-release.zip ) and admin/admin worked for me.

**Comment by stevespringett** [comment]
v3.0 will also use the same type of directory structure. Although it defaults to ~/.dependency-track
