### ISSUE TITLE
Import libraries from Dependency-Check

### ISSUE THREAD

**Issue by stevespringett** [stevespringett/dependency-track#4]
Auto-populate Dependency-Track database with library identification from Dependency-Check

**Comment by willpowerforever** [comment]
Could I know the progress of this? This one is important. We've already have lots of dependencies. It is will be best if you can have those dependencies imported into Dependency Track.

**Comment by stevespringett** [comment]
I have not started work on this. When I do, you'll see commit messages as part of the ticket.

**Comment by stevespringett** [comment]
Foundation of this provided by 673c7d2 Much more cleanup to do, but feature-wise, the functionality is there.
