### ISSUE TITLE
Add key/value store per application

### ISSUE THREAD

**Issue by stevespringett** [stevespringett/dependency-track#40]
Organizations that want to track attributes that are application specific should be able to do so via the UI and API.

@jtmelton

**Comment by stevespringett** [comment]
Viewing details for a project without key/value properties:
![screen shot 2017-12-20 at 11 04 24 am](https://user-images.githubusercontent.com/3878933/34239020-6ab809bc-e5ca-11e7-9720-75027ce13fc0.png)

Viewing details for a project with key/value properties:
![screen shot 2017-12-20 at 11 04 47 am](https://user-images.githubusercontent.com/3878933/34239048-86039e5c-e5ca-11e7-8daf-f5ea34ee5188.png)

**Comment by jtmelton** [comment]
This is great @stevespringett - thanks for the heads up!
