### ISSUE TITLE
Empty screens and Connection reset error when downloading NIST CVE data

### ISSUE THREAD

**Issue by securestep9** [stevespringett/dependency-track#45]
Hi, I have downloaded the v1.0 GA using link from

https://www.owasp.org/index.php/OWASP_Dependency_Track_Project

Deployed with Tomcat7. All component/vendor dropdowns are blank. Checked the logs and they say:

2017-01-07 12:14:39,363 INFO [pool-1-thread-1] [NistDataMirrorUpdater.java:111] 
Downloading https://nvd.nist.gov/download/nvdcve-2007.xml.gz
2017-01-07 12:14:39,670 WARN [pool-1-thread-1] [NistDataMirrorUpdater.java:133] 
An error occurred during the download or saving of NIST XML data: Connection res
et
2017-01-07 12:14:39,671 INFO [pool-1-thread-1] [NistDataMirrorUpdater.java:111] 
Downloading https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2007.xml.gz
2017-01-07 12:14:39,984 WARN [pool-1-thread-1] [NistDataMirrorUpdater.java:133] 
An error occurred during the download or saving of NIST XML data: Connection res
et
2017-01-07 12:14:39,984 INFO [pool-1-thread-1] [NistDataMirrorUpdater.java:111] 
Downloading https://nvd.nist.gov/download/nvdcve-2008.xml.gz
2017-01-07 12:14:40,309 WARN [pool-1-thread-1] [NistDataMirrorUpdater.java:133] 
An error occurred during the download or saving of NIST XML data: Connection res
et
2017-01-07 12:14:40,310 INFO [pool-1-thread-1] [NistDataMirrorUpdater.java:111] 
Downloading https://nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2008.xml.gz
2017-01-07 12:14:40,837 WARN [pool-1-thread-1] [NistDataMirrorUpdater.java:133] 
An error occurred during the download or saving of NIST XML data: Connection res
et
2017-01-07 12:14:40,838 INFO [pool-1-thread-1] [NistDataMirrorUpdater.java:111] 
Downloading https://nvd.nist.gov/download/nvdcve-2009.xml.gz
2017-01-07 12:14:41,325 WARN [pool-1-thread-1] [NistDataMirrorUpdater.java:133] 
An error occurred during the download or saving of NIST XML data: Connection res
et

There is no issue when downloading the files using curl/wget (e.g. Internet connection is fine!)

**Comment by KonstantinShemyak** [comment]
_2017-01-07 12:14:41,325 WARN [pool-1-thread-1] [NistDataMirrorUpdater.java:133]
An error occurred during the download or saving of NIST XML data: Connection res
et_
Are you behind HTTP proxy?

_All component/vendor dropdowns are blank._
DependencyTrack does not populate them (even when successfully downloaded NVD data). The user is supposed to type in the vendors and components.

**Comment by stevespringett** [comment]
Also, ensure you're running on Java 8. Java 7 does not support TLS 1.2 by default, which is now a requirement of the NVD. Also, various versions of OpenJDK 8 also have TLS problems. Use of Oracle Java 8 is recommended.

**Comment by securestep9** [comment]
This installation is not behind any proxy server. Java version used is OpenJDK 1.8_111

Steve, if this is such a widespread  problem this should be reflected in documentation. I totally understand the TLS1.2 issue, however this means that huge number of Open Source advocates (including us, OWASP folks) are going to have OpenJDK rather that Oracle Java installed and will inevitably run into "Connection reset" errors. I believe you should put Oracle Java 1.8u121 as System Requirements. At the moment your Getting Started page does not mention TLS 1.2 /Java Oracle Java issue at all: https://github.com/stevespringett/dependency-track/wiki/Getting-Started
