### ISSUE TITLE
Missing javascript assets

### ISSUE THREAD

**Issue by alefq** [stevespringett/dependency-track#50]
When trying to run 3.0-dev branch, the login page gets blank. 
Checking browser developer tools, there are two files with 404 HTTP status. 
```
/assets/functions.js
/assets/bind.min.js
```

I tried two approaches, with same results: 

1. deploying to a fresh tomcat instance
2. running through docker

Those files aren't available in the repository.

**Comment by stevespringett** [comment]
Thanks for the info and in-fact, you are correct. Those files are not yet checked in. 

I am currently concentrating on the REST APIs of the backend before I starting work on the frontend. The APIs are coming together nicely, as is the data model to support them. Currently (if the files were checked in) the login works, and the 'about' tab works. Not much else.

**Comment by alefq** [comment]
We can help you with some tickets for the new version. Since we saw that other branches are outdated (and to be deprecated), we are interested in having this project working, speccially the automated parts for tracking projects vulnerabilities.
At the moment, I only see #8 labeled as _help-wanted_, but as first step I tried to run the project when I got the difficulty mentioned in this issue.
Let me know how we can help you.

**Comment by stevespringett** [comment]
#8 I really want a solution for, something that doesn't rely on an external build system (like Maven for example).

I'm glad you're also interested in having the automation piece work first. That is also my interest as well. Visualizing the results will come later. I'm currently making changes to the data model and building up the REST resources to support the kinds of automation I believe will be necessary.

For the time being, be prepared to wipe the database every time you sync up and rebuild. There will likely be more changes tonight or tomorrow as well. 

The REST API is my first focus and will likely be stabilized in the next few weeks. This will provide the ability to ingest DC reports, process those reports, and continually analyze the components on an ongoing basis (even without further uploads). You'll also be able to get the current vulns (or vulns from a report) over REST. Once all that works, I'll begin working on the UI, which should be relatively soon.

Once things stabilize a bit, I will start adding more enhancement tickets to track the progress.
