### ISSUE TITLE
Add ability to import dependencies

### ISSUE THREAD

**Issue by swright-owasp** [stevespringett/dependency-track#52]
It would be a really useful feature to be able to import dependencies via an XML file. These could be XML files generated by OWASP Dependency Check as well as some other generic format. This would be helpful to automate the tracking of dependencies in one's system.

**Comment by stevespringett** [comment]
Although the DC report file is useful, it's doesn't actually provide a bill of materials per se. It can be used (and it is) but due to being evidence-based, it doesn't always resolve correctly.

I like the idea to provide a standardized format for defining dependencies. I'm not aware of any standard that exists for describing components in a BOM, so I think this solution should be to:

- Define an XML or JSON schema that defines components. It should describe the components used for a specific project.
- Create a parser and corresponding importer for the BOM format
- Create a REST resource that can import the components into a project
- Investigate the possibility of importing BOM results from other build systems. The Maven Dependency plugin can retrieve all runtime and provided dependencies. Node.js has similar functionality, although I'm not sure of their respective output formats.

**Comment by stevespringett** [comment]
@jeremylong Do you know of any existing standard that exists that defines software/components BOM?

**Comment by stevespringett** [comment]
I typically associate SPDX with only licenses, but realize it may actually be useful for this feature. Need to investigate the possibility of using SPDX in this context, and if so, check on the availability of existing parsers for Java.

**Comment by jeremylong** [comment]
In my initial research SPDX seemed like the best choice.

Jeremy

On Mar 19, 2017 3:52 PM, "Steve Springett" <notifications@github.com> wrote:

I typically associate SPDX with only licenses, but realize it may actually
be useful for this feature. Need to investigate the possibility of using
SPDX in this context, and if so, check on the availability of existing
parsers for Java.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/stevespringett/dependency-track/issues/52#issuecomment-287642496>,
or mute the thread

**Comment by KonstantinShemyak** [comment]
+1 for dependency import, together with dependency export into that same format. This would give users possibility to create backups of their DT installations, copy/migrate components from one installation to another, and so on.

**Comment by stevespringett** [comment]
SPDX license support is already included in DTv3 dev branch and I'm working on support for importing SPDX (both RDF and tag SPDX files). Writing valid SPDX (in either format) is actually quite complex and very little support for it exists outside of the SPDX tools themselves. The licensing seems to be the most prevalent use case. Nonetheless, I've added SPDX license support (with a resolver) and the component importer will also be supported in the future as well.

But I think a lightweight component definition format that describes a software bill of materials is necessary. Here's my initial thought:

```json
{
  "bom-version": "1.0.0",
  "components": [
    {
      "publisher": "Apache Software Foundation",
      "group": "org.apache.commons",
      "name": "commons-lang3",
      "version": "3.5",
      "scope": "compile",
      "packaging": "jar",
      "sha1": "6c6c702c89bfff3cd9e80b04d668c5e190d588c6",
      "description": "Apache Commons Lang3",
      "licenseId": "Apache-2.0",
      "modified": false,
      "language": "java"
    },
    {
      "author": "Nick Campbell",
      "name": "bcrypt",
      "version": "1.0.2",
      "scope": "dependencies",
      "packaging": "package.json",
      "description": "A bcrypt library for NodeJS",
      "licenseId": "MIT",
      "modified": false,
      "language": "javascript"
    }
  ]
}
```

JSON Schema:
```json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {},
    "id": "http://example.com/example.json",
    "properties": {
        "bom-version": {
            "id": "/properties/bom-version",
            "type": "string"
        },
        "components": {
            "id": "/properties/components",
            "items": {
                "id": "/properties/components/items",
                "properties": {
                    "description": {
                        "id": "/properties/components/items/properties/description",
                        "type": "string"
                    },
                    "group": {
                        "id": "/properties/components/items/properties/group",
                        "type": "string"
                    },
                    "language": {
                        "id": "/properties/components/items/properties/language",
                        "type": "string"
                    },
                    "licenseId": {
                        "id": "/properties/components/items/properties/licenseId",
                        "type": "string"
                    },
                    "modified": {
                        "id": "/properties/components/items/properties/modified",
                        "type": "boolean"
                    },
                    "name": {
                        "id": "/properties/components/items/properties/name",
                        "type": "string"
                    },
                    "packaging": {
                        "id": "/properties/components/items/properties/packaging",
                        "type": "string"
                    },
                    "publisher": {
                        "id": "/properties/components/items/properties/publisher",
                        "type": "string"
                    },
                    "scope": {
                        "id": "/properties/components/items/properties/scope",
                        "type": "string"
                    },
                    "sha1": {
                        "id": "/properties/components/items/properties/sha1",
                        "type": "string"
                    },
                    "version": {
                        "id": "/properties/components/items/properties/version",
                        "type": "string"
                    }
                },
                "type": "object"
            },
            "type": "array"
        }
    },
    "type": "object"
}
```

Any thoughts or comments on the format?

**Comment by KonstantinShemyak** [comment]
Looks fine, nothing wrong spotted (by a casual user).

**Comment by javabeanz** [comment]
Isn't is easier to use the mvn help:effective-pom functionality as BOM ?

**Comment by stevespringett** [comment]
@javabeanz a BOM definition (like SPDX) should not be confined to a specific language, build system, or platform. Dependency-Track isn't confined to the Java ecosystem, so the BOM format shouldn't be either. There are many platforms that do not support Java (like iOS), and even the ones that do, there are so many other languages choices.

**Comment by stevespringett** [comment]
I've started a pseudo working-group called CycloneDX to define a lightweight component identification format. All discussions regarding the component format should be directed to https://github.com/CycloneDX/specification

**Comment by eoftedal** [comment]
What I would really like to see in such a format is the ability to include a "reason" why the file was included. How was the dependency added? What kind of version specifier was used? In a graph database the edge should contain that information, but I'm not sure what the plans are here.
Why is this useful?
If component A depends on component B@2.0.3, and B version 2.0.0-2.0.3 has a vulnerability, then the dependency would have to be updated in A once 2.0.4 (the patched library) is released. If however A depends on B@2.0.x or B@2.x.x, then there is no need to change A.

**Comment by stevespringett** [comment]
Dependencies can now be imported using valid CycloneDX or SPDX documents using the REST API (/v1/bom). I plan on making this functionality exposed via the Dependency-Check Jenkins plugin as well (Dependency-Track Publisher).
