### ISSUE TITLE
dependency-check

### ISSUE THREAD

**Issue by Pamir** [stevespringett/dependency-track#55]
Hi,

dev-03 branch uses older version of dependency-check plugin. While using dependency-track it will be good to set maven local repository to get the benefit of dependency-check remote nexus  analyzer.
company : groupId
artifact: artifactId
version: version

This way Sha1 will be gathered from file system.

Kind Regards
Pamir

**Comment by stevespringett** [comment]
Can you clarity?

Are you referring to the use of Dependency-Check as part of the Dependency-Track build (via the dependency-check Maven profile)? Or are you referring to the embedded use of Dependency-Check core by Dependency-Track?

Maybe explain a bit what you envision and the benefit.

**Comment by Pamir** [comment]
Hi Steve,

I debugged dependency-track dev03 and stable branches. While executing background thread for java dependencies, NexusAnalayzer of the dependency-check is not working as expected. Dependency track does not know the SHA1's and appends NULL string to dependency name and artifactId's. It passes these parameters to dependency-check. NexusAnalayzer does not find the searched artifact from Nexus Repo. So dependency check does not gather the cves. By this way dependency-track does not show cves on the dashboard.

Kind Regards
Pamir

**Comment by rajeshramesh** [comment]
Hello Steve,
I am trying the stable build on my system and whenever I add a new component, CPE analyzer fails to recognize it and says an unexpected error occurred during analysis of 'NUL'

Here is the stack trace:
28-Aug-2017 15:45:39.528 INFO [SimpleAsyncTaskExecutor-6] org.owasp.dependencycheck.analyzer.CentralAnalyzer.checkEnabled Central analyzer disabled
28-Aug-2017 15:45:39.531 INFO [SimpleAsyncTaskExecutor-6] org.owasp.dependencycheck.Engine.doUpdates Checking for updates
28-Aug-2017 15:45:41.469 INFO [SimpleAsyncTaskExecutor-6] org.owasp.dependencycheck.Engine.doUpdates Check for updates complete
28-Aug-2017 15:45:41.983 INFO [SimpleAsyncTaskExecutor-6] org.owasp.dependencycheck.Engine.analyzeDependencies Analysis Starting
28-Aug-2017 15:45:43.113 SEVERE [SimpleAsyncTaskExecutor-6] org.owasp.dependencycheck.Engine.initializeAnalyzer Exception occurred initializing CPE Analyzer.
28-Aug-2017 15:45:43.131 WARNING [SimpleAsyncTaskExecutor-6] org.owasp.dependencycheck.Engine.analyzeDependencies An unexpected error occurred during analysis of 'NUL'
28-Aug-2017 15:45:43.670 INFO [SimpleAsyncTaskExecutor-6] org.owasp.dependencycheck.Engine.analyzeDependencies Analysis Complete

**Comment by stevespringett** [comment]
This part of of the code is likely still incomplete, as I've been focusing on architecture, REST APIs, and bulk importing. I plan on working on the scanning engine integration in the next week or two so these issues should be resolved shortly.

**Comment by stevespringett** [comment]
FYI, I'm currently working off an unpublished version of Dependency-Check 3.0.0 so I cannot push changes just yet, but the integration is nearly complete. 

@Pamir There's no need to set a Maven path since the hashes are already being captured and stored in the database, and (with DT 3.0) the Nexus analyzer can be configured by optionally loading the dependency-check.properties file. By default, the Maven Central analyzer will be enabled and Nexus disabled, but Nexus can be enabled and configured to point to a local Nexus Pro instance.

This commit https://github.com/jeremylong/DependencyCheck/commit/c4726088763153ea05735837de6cf9e8ad4a171b made this possible.

**Comment by stevespringett** [comment]
@Pamir An optional dependency-check.properties file can be included in the ~/.dependency-track/dependency-check directory. If this file exists, the properties included in it will be merged into the the properties Dependency-Track uses when executing Dependency-Check. For this specific ticket, I'd recommend the file containing only the following:

```ini
analyzer.nexus.enabled=true
analyzer.nexus.url=https://nexus.example.com/service/local/
analyzer.nexus.proxy=false
```

Do not copy the entire dependencycheck.properties file from dependency-check. Doing so will result in ODT/ODC not working correctly.
