### ISSUE TITLE
v3.0-dev fails to start after f1afad42

### ISSUE THREAD

**Issue by KonstantinShemyak** [stevespringett/dependency-track#56]
After commit f1afad42, DTrack fails to deploy with the following message:
```
SEVERE: An exception was thrown while adding/validating class(es) : Constraint "SCAN_UUID_IDX" already exists; SQL statement:
ALTER TABLE SCAN ADD CONSTRAINT SCAN_UUID_IDX UNIQUE (UUID) [90045-176]
org.h2.jdbc.JdbcSQLException: Constraint "SCAN_UUID_IDX" already exists; SQL statement:
ALTER TABLE SCAN ADD CONSTRAINT SCAN_UUID_IDX UNIQUE (UUID) [90045-176]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
        at org.h2.message.DbException.get(DbException.java:178)
...
```

Full app server log after a fresh start attached (extension 'txt' added as required by Github).

[catalina.out.txt](https://github.com/stevespringett/dependency-track/files/990734/catalina.out.txt)

**Comment by stevespringett** [comment]
Was this on an empty database? ~/dependency-track/db.h2.db will be created on initial startup. Does this error occur at that time?

**Comment by KonstantinShemyak** [comment]
The error occurs at the initial startup. To start clean, I do the following:

1. undeploy DTrack
2. stop Tomcat
3. `rm -rf ~/dependency-track`
4. start Tomcat
5. deploy DTrack.

The deployment fails with the given error.

**Comment by stevespringett** [comment]
Actually, my mistake, the directory is: ~/.dependency-track with a dot

Other than that, the procedure looks correct

**Comment by KonstantinShemyak** [comment]
In fact that was **my** mistake too, naturally above I meant, and removed, `~/.dependency-track` :-)

**Comment by stevespringett** [comment]
Closing. If the issue persists on the master branch, go ahead and reopen.
