### ISSUE TITLE
docker image

### ISSUE THREAD

**Issue by javabeanz** [stevespringett/dependency-track#57]
please create a Docker image with the dependency-track deployed

**Comment by stevespringett** [comment]
A dockerfile already exists, but I do plan on making an official release of it to Docker Hub

**Comment by MichaelGissingNC** [comment]
@stevespringett do you have the Dockerfile published somewhere?

**Comment by stevespringett** [comment]
@MichaelGissingNC I plan on changing the dockerfile a bit and publishing it to dockerhub once beta's of 3.0 are available in the fall.

**Comment by stevespringett** [comment]
Once RC's are available, I'll start publishing containers to https://hub.docker.com/r/owasp/dependency-track/

**Comment by geoffwhittington** [comment]
:+1:  I don't have a Java build environment, but I can get a Docker image running.

**Comment by stevespringett** [comment]
Just an update on this ticket… A Beta-1 image will be pushed to Docker Hub in 2-3 weeks time.

**Comment by davidkarlsen** [comment]
With staged builds [1] it should now be easy to have tooling for build in one stage, then publish the consumer image in a second stage and setup automated/trusted [2] build on docker hub.

[1]
https://docs.docker.com/engine/userguide/eng-image/multistage-build/

[2]
https://docs.docker.com/docker-hub/builds/

**Comment by stevespringett** [comment]
The conventions Dependency-Track will use with regards to Docker are:

- 'latest' tag, which is pulled by default if no tag is specified, will always refer to the latest stable release (3.0.0, 3.0.1, 3.1.0, etc)
- 'snapshot' tag will be built and pushed on all CI changes to the master. Use this if you want a "moving target" with all the latest changes.
- Version tags (3.0.0, 3.0.1, etc) will be used to indicate each release

For the betas, I will be using the 'snapshot' tag exclusively until the release of 3.0.0.  I'm going to treat the betas as a continuous moving target until we reach a stable release.

**Comment by stevespringett** [comment]
Snapshot releases are now being continuously delivered (via CI) to https://hub.docker.com/r/owasp/dependency-track/

The projects README has been updated with instructions on how to use the image.

https://twitter.com/DependencyTrack/status/960730100777082880
