### ISSUE TITLE
Automate data provisioning

### ISSUE THREAD

**Issue by elenoir** [stevespringett/dependency-track#67]
Is there any plan to automate the provisioning of all the informations needed by Dtrack in order to avoid fulfill everything manually (in case of complete information system containing plenty of applications) ?

**Comment by AdilusPrimus** [comment]
We're also interested by that feature here.
Was there a challenge to implement that feature or was it not just needed?
Please advise!

**Comment by stevespringett** [comment]
v3 (currently in active development) has an API-first design. It can ingest dependency-check-report.xml files today. If you use the Jenkins plugin, it already has a publish to Dependency-Track option.

v3 will also be able to ingest [CycloneDX](https://github.com/CycloneDX/specification) and will have some support for [SPDX](https://spdx.org/) as well. If neither of these work for you, the complete REST API has Swagger 2 docs so you can write your own integrations if you choose.

Refer to #52 for history of the feature request.
