### ISSUE TITLE
Error when building the 3.0-dev branch

### ISSUE THREAD

**Issue by adunkey** [stevespringett/dependency-track#75]
Hi,

Pulled the latest code this morning & get the following error:

SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.186 s <<< FAILURE! - in org.owasp.dependencytrack.model.ProjectTest
[ERROR] testProjectPersistence(org.owasp.dependencytrack.model.ProjectTest)  Time elapsed: 0.89 s  <<< ERROR!
javax.jdo.JDOFatalUserException: A property named javax.jdo.PersistenceManagerFactoryClass must be specified, or a jar file with a META-INF/services/javax.jdo.PersistenceManagerFactory entry must be in the classpath, or a property named javax.jdo.option.PersistenceUnitName must be specified.
Caused by: javax.jdo.JDOFatalInternalException: Error creating transactional connection factory
Caused by: java.lang.reflect.InvocationTargetException
Caused by: org.datanucleus.exceptions.NucleusException: Attempt to invoke the "DBCP" plugin to create a ConnectionPool gave an error : The connection pool plugin of type "DBCP" was not found in the CLASSPATH!
Caused by: org.datanucleus.exceptions.NucleusUserException: The connection pool plugin of type "DBCP" was not found in the CLASSPATH!

Thanks,

AD

**Comment by stevespringett** [comment]
Are you using Java 8 and Maven 3.1 or higher?

**Comment by stevespringett** [comment]
I'm unable to replicate

```
git clone -b 3.0-dev https://github.com/stevespringett/dependency-track.git dependency-track
cd dependency-track
mvn clean package
```

Travis-ci does a very similar thing https://travis-ci.org/stevespringett/dependency-track

In my case, I using Maven 3.5.0 with Java 1.8.0_144

**Comment by adunkey** [comment]
updated my maven & java & built the war successfully - thanks!

**Comment by adunkey** [comment]
Pulled the latest 3.0 branch & get this error @ the end:

INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/dependency-track-3.0-dev/dependency-track/src/main/java/org/owasp/dependencytrack/model/About.java:[36,
96] cannot find symbol
  symbol:   variable APPLICATION_NAME
  location: class alpine.Config.AlpineKey
[ERROR] /C:/dependency-track-3.0-dev/dependency-track/src/main/java/org/owasp/dependencytrack/model/About.java:[37,
92] cannot find symbol
  symbol:   variable APPLICATION_VERSION
  location: class alpine.Config.AlpineKey
[ERROR] /C:/dependency-track-3.0-dev/dependency-track/src/main/java/org/owasp/dependencytrack/model/About.java:[38,
94] cannot find symbol
  symbol:   variable APPLICATION_TIMESTAMP
  location: class alpine.Config.AlpineKey
[INFO] 3 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:36 min
[INFO] Finished at: 2017-11-08T09:33:35Z
[INFO] Final Memory: 32M/190M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on pr
oject dependency-track: Compilation failure: Compilation failure:
[ERROR] /C:/dependency-track-3.0-dev/dependency-track/src/main/java/org/owasp/dependencytrack/model/About.java:[36,
96] cannot find symbol
[ERROR]   symbol:   variable APPLICATION_NAME
[ERROR]   location: class alpine.Config.AlpineKey
[ERROR] /C:/dependency-track-3.0-dev/dependency-track/src/main/java/org/owasp/dependencytrack/model/About.java:[37,
92] cannot find symbol
[ERROR]   symbol:   variable APPLICATION_VERSION
[ERROR]   location: class alpine.Config.AlpineKey
[ERROR] /C:/dependency-track-3.0-dev/dependency-track/src/main/java/org/owasp/dependencytrack/model/About.java:[38,
94] cannot find symbol
[ERROR]   symbol:   variable APPLICATION_TIMESTAMP
[ERROR]   location: class alpine.Config.AlpineKey
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

Thanks,
AD

**Comment by stevespringett** [comment]
Correct. This is due to changes I made in Alpine last night that I need to update Dependency-Track for today. Will ping this ticket when those changes are made.

**Comment by stevespringett** [comment]
Closing
