### ISSUE TITLE
Issue with manually adding/removing components to the project

### ISSUE THREAD

**Issue by rajeshramesh** [stevespringett/dependency-track#85]
I am trying the latest build of dependency-track. I have created a new project and started adding components but these added components are not getting displayed in the project->components page. The added components are visible only in the List of components page. So the created projects always has 0 components.

**Comment by stevespringett** [comment]
I don't think this functionality is fully working just yet. I'm currently working on some other enhancements to components (hashs, purl, etc) and will be completing this functionality soon.

If you want to import Dependency-Check XML results into Dependency-Track, those components WILL be displayed in the projects view (in addition to the components view). It's just the manual adding of them isn't fully functional yet.

**Comment by stevespringett** [comment]
The original issue reported has been implemented. It's now possible to create a dependency from an existing component or by creating a new component.

![screen shot 2018-01-18 at 11 55 20 pm](https://user-images.githubusercontent.com/3878933/35136814-50256764-fcab-11e7-8e1d-a68db7f33416.png)

I'm leaving this issue open as I still have to implement the manual removal of dependencies from a project.
