### ISSUE TITLE
Rows Last Scanned, BOM Updated, Sub Projects & Versions not updated

### ISSUE THREAD

**Issue by adunkey** [stevespringett/dependency-track#89]
When uploading a dependency check scan from Jenkins, the fields Last Scanned, BOM Updated, Sub Projects & Versions are not populated. Please see screenshot attached.
![dependencytrack](https://user-images.githubusercontent.com/4255262/35505688-c4bf610c-04de-11e8-9fb9-5b12f112ce2a.PNG)

**Comment by stevespringett** [comment]
This is known and is due to these features still being incomplete.
